const PDFDocument = require("pdfkit");
const path = require("path");

module.exports = function generateResultPdf(res, data) {
  const doc = new PDFDocument({ margin: 50 });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=result-${Date.now()}.pdf`
  );

  doc.pipe(res);

  const logoPath = path.join(__dirname, "../image/logo.jpeg");

  doc.opacity(0.08);
  doc.image(logoPath, 120, 220, { width: 300 });
  doc.opacity(1);

  doc
    .fontSize(22)
    .fillColor("#00bcd4")
    .text("Test Result", { align: "center" })
    .moveDown()
    .fillColor("black");

  doc
    .fontSize(12)
    .text(`Name: ${data.userName}`)
    .text(`Test: ${data.testTitle}`)
    .text(`Date: ${new Date().toLocaleString()}`)
    .moveDown();

  doc
    .strokeColor("#00bcd4")
    .lineWidth(2)
    .moveTo(50, doc.y)
    .lineTo(550, doc.y)
    .stroke()
    .moveDown();

  doc
    .rect(50, doc.y, 500, 65)
    .fillOpacity(0.05)
    .fill("#00bcd4")
    .fillOpacity(1);

  doc
    .moveDown()
    .fontSize(14)
    .text(`Score: ${data.percentage}%`)
    .text(`Passed Test Cases: ${data.passedTCs}/${data.totalTCs}`)
    .text(`Performance: ${data.message}`)
    .moveDown();

  doc.fontSize(16).text("Question Summary").moveDown();

  data.answers.forEach((ans, index) => {
    doc
      .fontSize(13)
      .text(`${index + 1}. ${ans.questionId.title}`)
      .fontSize(10)
      .fillColor("gray")
      .text(ans.questionId.description)
      .fillColor("black")
      .fontSize(12)
      .text(`Passed: ${ans.passedTCs}/${ans.totalTCs}`)
      .moveDown();
  });

  doc
    .moveDown(2)
    .fontSize(10)
    .text("Generated by LogicGate", { align: "center" });

  doc.end();
};
